FROM node:20

RUN apt-get update && apt-get install -y openssl

RUN curl -fsSL https://bun.sh/install | bash

ENV PATH="/root/.bun/bin:$PATH"

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

CMD ["sh", "-c", "bun install"]
CMD ["sh", "-c", "bun generate-prisma && bun dev"]