FROM node:20

# Install openssl
RUN apt-get update && apt-get install -y openssl

# Install bun
RUN curl -fsSL https://bun.sh/install | bash

# Add bun to PATH
ENV PATH="/root/.bun/bin:$PATH"

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install npm dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Install bun dependencies
RUN bun install

# Define the start command
CMD ["sh", "-c", "bun generate-prisma && bun dev"]
